# Generated by Django 5.2.11 on 2026-02-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('service_provider', 'Service_provider'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=30),
        ),
        migrations.CreateModel(
            name='ProviderDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_full_day_busy', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.provider')),
            ],
        ),
    ]
