# Generated by Django 5.2.11 on 2026-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_provider_image_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, default='localservice.jpg', null=True, upload_to='providers/'),
        ),
    ]
