# Generated by Django 5.2.11 on 2026-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='localservice.jpg', upload_to='providers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('service_provider', 'Service_provider')], default='customer', max_length=30),
        ),
    ]
