# Generated by Django 5.2.11 on 2026-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_userprofile_address_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service_provider', 'Service_provider'), ('customer', 'Customer')], default='customer', max_length=30),
        ),
    ]
