# Generated by Django 5.2.11 on 2026-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_provider_location_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service_provider'), ('admin', 'Admin')], default='customer', max_length=30),
        ),
    ]
