# Generated by Django 5.2.11 on 2026-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='salary',
            field=models.CharField(blank=True, default='Based on Work', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('service_provider', 'Service_provider')], default='customer', max_length=30),
        ),
    ]
