# Generated by Django 5.2.11 on 2026-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_provider_salary_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('work pending', 'work Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='work pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('service_provider', 'Service_provider')], default='customer', max_length=30),
        ),
    ]
