# Generated by Django 5.2.11 on 2026-02-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.provider')),
            ],
        ),
    ]
